#first installed bwa
apt-get update
apt-get install bwa

#then installed samtools and bcftools
apt install samtools
apt install bcftools

#then installed pandas and matplotlib for visualization
import pandas as pd
import matplotlib.pyplot as plt
