#first installed bwa for comparison
RUN apt-get update
RUN apt-get install bwa

#then installed samtools and bcftools for analysis
RUN apt install samtools
RUN apt install bcftools

#then installed pandas and matplotlib for visualization
RUN import pandas as pd
RUN import matplotlib.pyplot as plt
